docs: add documentation for J1QL optional traversals
JupiterOne/docs pull request #111
Opened 2020-08-25 14:34 UTC by charlieduong94

2020-08-25 16:10 UTC, aiwilliams commented on docs/jupiterone-query-language.md
> +If the relationship does not exist, the `User` entity is returned.
The existing docs say:

> By default, the entities and their properties found from the start of the traversal is returned. For example, Find User that IS Person returns all matching User entities and their properties, but not the related Person entities.

I'm surprised that either the `Person` or the `User` is returned. What am I missing?

2020-08-31 14:51 UTC, charlieduong94 commented on docs/jupiterone-query-language.md
> +If the relationship does not exist, the `User` entity is returned.
Hey, sorry for the late response. I misinterpreted @erkangz 's vision of optional traversals and ended up using gremlin's built in `optional` step which used the coalescing behavior.. I have changed this now to union the optionally traversed entities and the entities they stemmed from, so both the `User` and optionally found `Person` entities are returned (no longer one or the other. This allows for a more informative graph to be displayed when visualizing subgraphs.

2020-09-01 17:49 UTC, aiwilliams commented on docs/jupiterone-query-language.md
> +unioned results. This query searches for AWS accounts or AWS IAM roles
```suggestion
Relationships that come after an optional traversal are processed on the
combined results. This query searches for AWS accounts or AWS IAM roles
```

2020-09-01 17:50 UTC, aiwilliams commented on docs/jupiterone-query-language.md
> +of each previous optional traversal will be used in the next optional
```suggestion
Optional traversals can also be chained. The combined results from
each previous optional traversal will be used in the next optional
```

2020-09-01 17:53 UTC, aiwilliams commented on docs/jupiterone-query-language.md
> +traversal to be unioned together and for additional constraints to be applied
```suggestion
traversal to be combined and for additional constraints to be applied
```

2021-01-13 21:35 UTC, charlieduong94 commented on docs/jupiterone-query-language.md
> +and `User` entities that do not have the indirect relationship to the `Device`.
In the below query, the result will return the `User` and `Device` devices indirectly related to the user from the optional traversal.

2021-01-14 15:26 UTC, philidem requested changes

2021-01-14 15:26 UTC, philidem commented on docs/jupiterone-query-language.md
> +find User (that IS Person)?
Minor: You use `find` here and `Find` in the next example. Might help to be consistent. I still prefer all upper case...

2021-01-14 15:26 UTC, philidem commented on docs/jupiterone-query-language.md
> +  (that is Person)? as UserOrPerson
We typically name aliases with a lower case letter so `userOrPerson` seems more consistent than `UserOrPerson`.

2021-01-14 15:26 UTC, philidem commented on docs/jupiterone-query-language.md
> +Where UserOrPerson.email = 'test@jupiterone.com'
Can you use `WITH` for an optional traversal? Might be worth providing an example that uses `WITH`. Do you have to use `WHERE` in this example?

2021-01-14 15:31 UTC, charlieduong94 commented on docs/jupiterone-query-language.md
> +Where UserOrPerson.email = 'test@jupiterone.com'
Yep will do

2021-01-14 15:31 UTC, charlieduong94 commented on docs/jupiterone-query-language.md
> +find User (that IS Person)?
:+1:

2021-01-14 15:31 UTC, charlieduong94 commented on docs/jupiterone-query-language.md
> +  (that is Person)? as UserOrPerson
good feedback, will do

2021-01-14 16:16 UTC, erkangz requested changes

2021-01-14 16:16 UTC, erkangz commented on docs/jupiterone-query-language.md
> +Relationships can still be chained within an optional traversal. The query
```suggestion
**Relationships can still be chained within an optional traversal.** The query
```

2021-01-14 16:16 UTC, erkangz commented on docs/jupiterone-query-language.md
> +```
```suggestion
**Relationships that come after an optional traversal are processed on the
combined results.** This query searches for Users or UserGroups that directly
assigned an AccessPolicy granting admin permissions to certain resources,
or via an AccessRole assigned to the User/UserGroup. 

```j1ql
Find (User | UserGroup)
  (that assigned AccessRole)?
  that assigned AccessPolicy
  that allows as permission *
where permission.admin=true
return TREE
```
```

2021-01-14 16:16 UTC, erkangz commented on docs/jupiterone-query-language.md
> +```
this is a more realistic example than the account trust one

2021-01-14 16:16 UTC, erkangz commented on docs/jupiterone-query-language.md
> +Optional traversals can also be chained. The combined results from
```suggestion
**Optional traversals can also be chained.** The combined results from
```

2021-01-14 16:16 UTC, erkangz commented on docs/jupiterone-query-language.md
> +The optional traversals can also be aliased. This allows the union set of
```suggestion
**The optional traversals can also be aliased.** This allows the union set of
```

2021-01-14 16:17 UTC, charlieduong94 commented on docs/jupiterone-query-language.md
> +```
Nice, thanks for the tweak!

2021-01-14 16:20 UTC, philidem approved these changes

2021-01-14 16:23 UTC, austinkelleher commented on docs/jupiterone-query-language.md
> +## Optional traversals
It would be kinda nice if we prefixed beta features in the Markdown header to make it immediately clear without having to describe in each section. e.g.

```
## (Beta) Optional Traversals
```

2021-01-14 16:23 UTC, austinkelleher commented on docs/jupiterone-query-language.md
> +## Optional traversals
Or 

```
## Optional Traversals (Beta)
```

2021-01-14 16:25 UTC, charlieduong94 commented on docs/jupiterone-query-language.md
> +## Optional traversals
Good suggestion. I think I prefer the postfixing

2021-01-14 16:39 UTC, erkangz approved these changes

2021-01-14 16:42 UTC, merged