Add person-team-relationship example
JupiterOne/docs pull request #148
Opened 2021-01-09 07:16 UTC by jayson-jensen-pro

Please provide branch naming feedback and any other feedback as I am making my first PR. This guide is to help users upload Team entities and create relationships to Person entities.

2021-01-10 19:42 UTC, a-u-h-g commented on docs/person-team-relationship.md
> +
Would be good to have a preamble describing why someone might want to do this.

2021-01-10 19:43 UTC, a-u-h-g commented on docs/person-team-relationship.md
> +![bulk-upload](../assets/bulk-upload.png)
Link also to the bulk upload API and suggest it can be done via UI or API

2021-01-10 19:44 UTC, a-u-h-g requested changes
Please address inline comments - great job taking initiative.

2021-01-11 15:02 UTC, erichs commented on docs/person-team-relationship.md
> +![bulk-upload](../assets/bulk-upload.png)
Is there *additional* API documentation for Bulk Upload other than https://support.jupiterone.io/hc/en-us/articles/360049348293?

2021-01-12 23:31 UTC, a-u-h-g approved these changes

2021-01-12 23:59 UTC, erkangz requested changes

2021-01-12 23:59 UTC, erkangz commented on docs/person-team-relationship.md
> +# Mapping Person Entities to a Team Entity
```suggestion
# Creating `Team` entities and mapping team members
```

2021-01-12 23:59 UTC, erkangz commented on docs/person-team-relationship.md
> +This guide walks through the process of mapping Person(s) entities (already integrated via SSO/IdP providers) to a custom Team.
```suggestion
This guide walks through the process of creating `Team` entities and mapping 
team members to the `Person` entities (that are already integrated via SSO/IdP 
providers) to each team.

This can be accomplished by uploading a JSON/YAML document containing the
`Team` entities either via the JupiterOne app UI or the platform API.
```

2021-01-12 23:59 UTC, erkangz commented on docs/person-team-relationship.md
> +     "members": [
It could be good to add explanation below the example code block to explain that:

- `"members"` are mapped to `Person` entities by email, creating `Team -HAS-> Person` relationships
- `"lead"` or `"manager"` or `"supervisor"` is also mapped to a `Person` entity by email, creating `Person -MANAGES-> Team` relationships

2021-01-12 23:59 UTC, erkangz commented on docs/person-team-relationship.md
> +```
```suggestion
```json
```

2021-01-12 23:59 UTC, erkangz commented on docs/person-team-relationship.md
> +This process can also be accomplished via the JupiterOne API using the JSON example above. See the document [Bulk Upload][bulk-upload-api] for more info.
please add hard line wrap for long lines

2021-01-13 18:55 UTC, a-u-h-g approved these changes

2021-01-13 19:35 UTC, erkangz approved these changes

2021-01-13 19:35 UTC, merged