Soc2 with jupiterone
JupiterOne/docs pull request #168
Opened 2021-02-16 16:32 UTC by tanggk

@jayson-jensen-pro please finalize review
@a-u-h-g please review after Jayson

@a-u-h-g within step 5. 'Review evidence mapping', my ordered list structure I think has too many levels where markdown may not support it; please confirm (alternative options would be greatly appreciated)

next step after your guys' reviews would be for Erkang to review before publishing this support article to Zendesk.

2021-02-16 16:52 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +Review all of the templated, out-of-the-box policies + procedures, ensuring they accurately represent your organization’s principles/processes, tailoring and/or adding your own documentation where re
Should we recommend how to use the instructions section here if we're deploying the change around the same time?

2021-02-16 16:53 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +Import the **SOC 2 Security Controls** compliance framework within the Compliance app. There is the functionality within JupiterOne to add controls, removal controls, and/or update control wording.
*remove

2021-02-16 16:56 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +Link within the app: [https://j1.apps.us.jupiterone.io/integrations](https://j1.apps.us.jupiterone.io/integrations)
Instead of "Link within the app"... I'm trying to think of a better way to call this out.

2021-02-16 16:58 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +            2. Mapping a prewritten, templated query (over 400 are in our library)
You could combine these bullets and then below have a section called "New Query" with the corresponding support links and then "Map a Prewritten Query" with its link

2021-02-16 17:00 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +        4. Upload additional evidence, e.g., spreadsheets, compressed files, etc.
don't need etc. when using e.g.

2021-02-16 17:37 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +Hovering over any of the 3x progress bars will provide a more detailed summary, with any of the reported details, clickable to quickly filter all of the controls with the same status:
3x? or just 3?

2021-02-16 17:38 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +- Exporting evidence per control
Exporting evidence for a single control

2021-02-16 17:39 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +- Exporting evidence for all controls within the SOC 2 framework, either as a summary, or the entire evidence output
Exporting evidence across all controls...

2021-02-16 17:40 UTC, jayson-jensen-pro commented on guides/soc2-with-jupiterone.md
> +You can invite internal team members or external users, e.g., auditors, into your JupiterOne instance/environment:
. instead of :

2021-02-16 20:47 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Link within the app: [https://j1.apps.us.jupiterone.io/integrations](https://j1.apps.us.jupiterone.io/integrations)
@a-u-h-g thoughts?

2021-02-16 20:54 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +        4. Upload additional evidence, e.g., spreadsheets, compressed files, etc.
I looked it up - I  think both are fine. do you prefer I remove 'etc.'?

2021-02-16 20:55 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Hovering over any of the 3x progress bars will provide a more detailed summary, with any of the reported details, clickable to quickly filter all of the controls with the same status:
rewrote as 'three (3)'

2021-02-16 20:55 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Import the **SOC 2 Security Controls** compliance framework within the Compliance app. There is the functionality within JupiterOne to add controls, removal controls, and/or update control wording.
updated

2021-02-16 20:55 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Review all of the templated, out-of-the-box policies + procedures, ensuring they accurately represent your organization’s principles/processes, tailoring and/or adding your own documentation where re
updated

2021-02-16 20:55 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +- Exporting evidence per control
updated

2021-02-16 20:55 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +You can invite internal team members or external users, e.g., auditors, into your JupiterOne instance/environment:
updated

2021-02-16 20:55 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +- Exporting evidence for all controls within the SOC 2 framework, either as a summary, or the entire evidence output
updated

2021-02-17 16:27 UTC, a-u-h-g requested changes

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Link within the app: [https://j1.apps.us.jupiterone.io/integrations](https://j1.apps.us.jupiterone.io/integrations)
How about, `[In-app Integrations Setup](https://apps.us.jupiterone.io/integrations)`
Note the URL shouldn't include `j1` or it will direct them to our prod environment. Link should look like this [In-app Integrations Setup](https://apps.us.jupiterone.io/integrations)

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Link within the app: [https://j1.apps.us.jupiterone.io/policies](https://j1.apps.us.jupiterone.io/policies)
"In-app Policies Setup" and the link should be: https://apps.us.jupiterone.io/policies
`[In-app Policies Setup](https://apps.us.jupiterone.io/policies)`

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +
Needs an instruction on how to import the templates first (fill out the required information)

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
Instead of "Existing" let's say "Additional support documentation:"

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
Instead of "Existing" let's say "Additional support documentation:"

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Link within the app: [https://j1.apps.us.jupiterone.io/compliance](https://j1dev.apps.us.jupiterone.io/compliance)
`[In-app Compliance Setup](https://apps.us.jupiterone.io/compliance)`

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
"Existing" -> "Additional"

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
"Existing" -> "Additional"

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +    2. If the evidence isn’t satisfactory, i.e., incorrect or incomplete:
Fun fact you can just use 1. for all the numbered lists and Markdown will auto increment. Helps with longer lists and if the doc is edited in the future by someone else there will never be mis-numberings.
1.
1.
renders as
1.
2.

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
"Existing" -> "Additional"

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
"Existing" -> "Additional"

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
"Existing" -> "Additional"

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
"Existing" -> "Additional"

2021-02-17 16:27 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +1. Link additional evidence, i.e., hyperlink
Better as:
1.
1.
1.
per comment earlier

2021-02-17 17:49 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +            2. Mapping a prewritten, templated query (over 400 are in our library)
I updated the format

2021-02-17 17:50 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Link within the app: [https://j1.apps.us.jupiterone.io/policies](https://j1.apps.us.jupiterone.io/policies)
updated

2021-02-17 17:51 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +
aren't the templated P+P already available presuming the customer goes through the normal J1 setup/onboarding UI workflow?

2021-02-17 17:52 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
updated

2021-02-17 17:52 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
updated

2021-02-17 17:53 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Link within the app: [https://j1.apps.us.jupiterone.io/compliance](https://j1dev.apps.us.jupiterone.io/compliance)
updated

2021-02-17 17:53 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
updated

2021-02-17 17:53 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
updated

2021-02-17 17:54 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
updated

2021-02-17 17:54 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
updated

2021-02-17 17:54 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
updated

2021-02-17 17:54 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +Existing support documentation:
updated

2021-02-17 20:30 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +
It is pretty easy to skip that step in the account creation process - most customers have to fill out the variables the first time the visit the policies page before they get the templated P+Ps populated.

2021-02-17 21:31 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +    2. If the evidence isn’t satisfactory, i.e., incorrect or incomplete:
this is a technical reason I can't do this for all of the ordered lists

2021-02-17 21:52 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +1. Link additional evidence, i.e., hyperlink
updated

2021-02-17 22:19 UTC, tanggk commented on guides/soc2-with-jupiterone.md
> +
updated

2021-02-17 22:30 UTC, a-u-h-g approved these changes
Awesome. Please link me this when the article is live. Want to send to customers.

2021-02-17 23:18 UTC, a-u-h-g commented on guides/soc2-with-jupiterone.md
> +    2. If the evidence isn’t satisfactory, i.e., incorrect or incomplete:
OK sounds good - I like how it is rendering with the outline format.

2021-02-18 20:35 UTC, merged