Ab#2548 custom query guide
JupiterOne/docs pull request #169
Opened 2021-02-17 22:21 UTC by jayson-jensen-pro

2021-02-22 21:26 UTC, tanggk commented on docs/jupiterone-custom-query-guide.md
> +questions, tweaking them as needed, then creating your own from scratch.
what about pointing out what existing resources are available for pre-canned q's?

2021-02-22 21:29 UTC, tanggk commented on docs/jupiterone-custom-query-guide.md
> +To start, navigate to the Landing page of JupiterOne and type in a basic query,
is this a formatting style that we can call out this is the actual start of the step-by-step instructions?

2021-02-22 21:29 UTC, tanggk commented on docs/jupiterone-custom-query-guide.md
> +## Variable Placeholders
how applicable are variable placeholders to queries in general, and then specifically for custom queries? just a q I have out of curiosity

2021-02-22 21:29 UTC, tanggk commented on docs/jupiterone-custom-query-guide.md
> +
I probably missed it but I presume these specific topics were requested to be incorporated into this general overarching 'custom query guide'?

2021-02-22 21:32 UTC, jayson-jensen-pro commented on docs/jupiterone-custom-query-guide.md
> +
Yes. The 3 level-2 subheadings were acceptance criteria.

2021-02-22 21:34 UTC, jayson-jensen-pro commented on docs/jupiterone-custom-query-guide.md
> +## Variable Placeholders
You can't use placeholders when you're typing in the query bar on the landing page. You can only access them via pre-saved queries. Not sure if that answers your question.

2021-02-22 21:34 UTC, jayson-jensen-pro commented on docs/jupiterone-custom-query-guide.md
> +To start, navigate to the Landing page of JupiterOne and type in a basic query,
Hmmm. Not sure, do you have any recommendations?

2021-02-22 21:36 UTC, jayson-jensen-pro commented on docs/jupiterone-custom-query-guide.md
> +questions, tweaking them as needed, then creating your own from scratch.
Are you recommending a link to this page? https://support.jupiterone.io/hc/en-us/articles/360038496974-Packaged-Questions-Catalog

2021-02-22 22:30 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +questions, tweaking them as needed, then creating your own from scratch.
all relevant links that could help them learn more should be interspersed in this article

2021-02-22 22:40 UTC, a-u-h-g requested changes

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +To start, navigate to the Landing page of JupiterOne and type in a basic query,
Use numbers

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +
Let's call it J1QL Tips and Tricks instead

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +**HINT** You can arrive at the same result using the relationship verb `RELATES
This still should be higher up in the article, before: "To start"

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +## When to Use WITH vs WHERE
Put this section first

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +`WITH` is used to filter **node** properties **pre-traversal**.
Define pre-traversal and use an example where it matters for example:
Find Person that OWNS Device that INSTALLED Application with name~="application"

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +**NOTE** Use `WITH` over `WHERE` when possible as the `WITH` operation is more
Put this note after explaining what Where does

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +`WHERE` is used to filter **node** properties **post-traversal**.
Define post-traversal

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +comparing the `name` property of one node against the `name` property of a
Explain that Where must be used for property comparisons before giving this example

2021-02-22 22:40 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +The query evaluates the relationship between a `Training` and a `User`, or the
Some properties in the graph are stored on the edges. This query checks the edge, `ASSIGNED`, and filters on its properties, in this case `completedOn`, and finds Trainings Assigned to Users where the completedOn date is undefined (or incomplete). You can see this in the graph - drop in a screenshot

2021-02-22 22:42 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +## Variable Placeholders
Let's make this section 2

2021-02-22 22:42 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +## Leveraging the Graph for Context
let's make this section 3

2021-02-22 22:43 UTC, a-u-h-g commented on docs/jupiterone-custom-query-guide.md
> +# Guide to Writing Custom J1QL Queries
J1QL Tips and Tricks instead

2021-02-24 18:22 UTC, a-u-h-g requested changes

2021-02-24 18:22 UTC, a-u-h-g commented on docs/j1ql-tips-and-tricks.md
> +Also keep in mind that when traversing the graph from a starting node, you may
This should be explained more clearly, it sounds contradictory to the thesis of this section. It sounds like you cannot traverse the graph to learn about the relationships to other nodes...

2021-02-24 18:22 UTC, a-u-h-g commented on docs/j1ql-tips-and-tricks.md
> +**HINT** To see all of the related entities from a single node, use the
This should be rephrased to be more of a "when in doubt about which verb to use to traverse an edge... `RELATES TO` is the catch all" and explain why you wouldn't want to use `Relates to` (slow because it checks all nodes as possible children every time it is used instead of just those connected by the specific edge verb.

2021-02-24 18:22 UTC, a-u-h-g commented on docs/j1ql-tips-and-tricks.md
> +
Open with a blurb about why someone might need to do this and link out to existing resources on J1QL here as well incase they don't have enough prior knowledge to make use of this. https://support.jupiterone.io/hc/en-us/articles/360022720434-4-9-J1QL-Query-Tutorial
For example a user may not know immediately which nodes or verbs to traverse the graph to connect different entities, for example how can you learn that Person OWNS Device, etc.

2021-02-24 18:22 UTC, a-u-h-g commented on docs/j1ql-tips-and-tricks.md
> +**Hint** Relationships can be queried bidirectionally. For example, `Find User
Maybe call "Hints" "**Tips**" to be on theme in this article.

2021-02-24 22:51 UTC, jayson-jensen-pro commented on docs/j1ql-tips-and-tricks.md
> +Find User as u1 that HAS UserGroup that ASSIGNED AccessRole that ASSIGNED User as u2 WHERE u1.name=u2.name
Thanks! I had a good starting query ;)

2021-03-02 19:01 UTC, a-u-h-g requested changes

2021-03-02 19:01 UTC, a-u-h-g commented on queries/adv-j1ql-tips-and-tricks.md
> +replacing `DataStore` with the entity class/type you are interested in.
```suggestion
in the example below, replace `DataStore` with the entity class/type you are interested in.
```

2021-03-02 19:01 UTC, a-u-h-g commented on queries/adv-j1ql-tips-and-tricks.md
> +of either `User` or `UserGroup` depending on which entity you `Find`.
```suggestion
of `User` for the former or `UserGroup` for the latter depending on which entity you `Find`.
```

2021-03-02 19:55 UTC, jayson-jensen-pro commented on queries/adv-j1ql-tips-and-tricks.md
> +2. `WHERE` can also be used to filter the relationship **edge** properties **post-traversal**.
Removed "be" from your suggestion.

2021-03-02 21:28 UTC, a-u-h-g requested changes

2021-03-02 21:28 UTC, a-u-h-g commented on queries/adv-j1ql-tips-and-tricks.md
> +```j1ql
Let's replace this code block with an image of where this query is saved in the Query Library with the mouseover buttons visible

2021-03-02 21:28 UTC, a-u-h-g commented on queries/adv-j1ql-tips-and-tricks.md
> +The placeholder double curly bracket syntax cannot be used in the search bar.
```suggestion
Variable placeholder syntax cannot be used directly in the search bar.
```

2021-03-02 21:28 UTC, a-u-h-g commented on queries/adv-j1ql-tips-and-tricks.md
> +- One or more placeholders can be used in a single saved query.
let's switch the order of these bullets

2021-03-02 21:28 UTC, a-u-h-g commented on queries/adv-j1ql-tips-and-tricks.md
> +**REMINDER**
```suggestion
**TIPS**
```

2021-03-02 23:54 UTC, a-u-h-g approved these changes

2021-03-03 00:35 UTC, merged