Ad2743 insights dashboards templates guide
JupiterOne/docs pull request #182
Opened 2021-02-26 22:58 UTC by tanggk

deleted old Insights articles + added new comprehensive guide

2021-02-26 23:49 UTC, jayson-jensen-pro commented on guides/insights-dashboards.md
> +   -type of visual chart, e.g., number, pie, line, bar, etc.\
If you want these to show up as an unordered list I believe you need to have a space between the dash and the first word.

2021-02-26 23:50 UTC, jayson-jensen-pro commented on guides/insights-dashboards.md
> +-Rename, clone, or delete boards:\
Same here for bullets

2021-02-27 23:01 UTC, erkangz commented on guides/insights-dashboards.md
> +   ![import-dashboard](../assets/import-dashboard.gif)
```suggestion
1. Navigate to the specific prebuilt dashboard you’d like to import into your
   JupiterOne account:
   
   <https://github.com/JupiterOne/insights-dashboards>
   
1. Pick the specific board, e.g., ‘AWS Accounts’

1. Click into ‘board.json’

1. Right click on ‘Raw’ -> ‘Save File’

   ![save-dashboard](../assets/save-dashboard.gif)
   
1. Navigate within JupiterOne to ‘Insights’ to add a board:

  - Expand the left sidebar by hitting the ‘>’ carrot 
  - Hit the ‘Add’ button’ + choose whether you want a personal or team board
  - Click ‘Upload From JSON Schema’ + select the file you previously saved
  
    ![import-dashboard](../assets/import-dashboard.gif)
```

2021-02-27 23:02 UTC, erkangz commented on guides/insights-dashboards.md
> +   ![custom-board](../assets/custom-board.gif)
```suggestion
Navigate within JupiterOne to ‘Insights’ to add a board:

1. Expand the left sidebar by hitting the ‘>’ carrot 

1. Hit the ‘Add’ button’ + choose whether you want a personal or team board

1. Click ‘Start Adding Charts’. This will open up the ‘Add Chart’ workflow where
   you can customize the details of your query/chart, which include, but aren't
   limited to:
   
   - type of visual chart, e.g., number, pie, line, bar, etc.
   - the chart’s query or queries
   - formatting options 
   
     ![custom-board](../assets/custom-board.gif)
```

2021-02-28 16:32 UTC, erkangz requested changes

2021-02-28 16:32 UTC, erkangz commented on guides/insights-dashboards.md
> +# Getting Started With Insights Dashboards
Always add empty line after heading (same for all headings below)

2021-02-28 16:32 UTC, erkangz commented on guides/insights-dashboards.md
> +This guide will walk through how to:
Always have empty line before list, same below

2021-02-28 16:32 UTC, erkangz commented on guides/insights-dashboards.md
> +Click ‘Apps’ + select ’Insights’\
the escape here `\` is unnecessary. Same below

2021-02-28 16:32 UTC, erkangz commented on guides/insights-dashboards.md
> +![clone-delete-rename](../assets/clone-delete-rename.png)
indent (add two spaces) here to keep the image within the list

2021-03-01 17:38 UTC, tanggk commented on guides/insights-dashboards.md
> +   ![import-dashboard](../assets/import-dashboard.gif)
I think lines 43 through 45 should be an ordered list/outline as they're steps that need to happen in that specific order @erkangz 

if I'm missing the intent of your suggestion, please let me know

2021-03-01 17:46 UTC, tanggk commented on guides/insights-dashboards.md
> +# Getting Started With Insights Dashboards
updated

2021-03-01 17:47 UTC, tanggk commented on guides/insights-dashboards.md
> +This guide will walk through how to:
updated

2021-03-01 17:49 UTC, tanggk commented on guides/insights-dashboards.md
> +Click ‘Apps’ + select ’Insights’\
my markdown previewer in VSCode seems to show otherwise? when I remove the escape, the image isn't on its own line

2021-03-01 17:49 UTC, tanggk commented on guides/insights-dashboards.md
> +![clone-delete-rename](../assets/clone-delete-rename.png)
I believe I made this change in the code but my markdown previewer in VS Code doesn't seem to reflect any visible changes

2021-03-02 16:40 UTC, tanggk commented on guides/insights-dashboards.md
> +   ![import-dashboard](../assets/import-dashboard.gif)
I made changes manually in code

2021-03-02 16:44 UTC, erkangz requested changes

2021-03-02 16:44 UTC, erkangz commented on guides/insights-dashboards.md
> +-Rename, clone, or delete boards:
```suggestion
- Rename, clone, or delete boards:
```
same for other bullet items below

2021-03-02 16:46 UTC, tanggk commented on guides/insights-dashboards.md
> +-Rename, clone, or delete boards:
I updated

2021-03-02 22:55 UTC, erkangz approved these changes

2021-03-02 22:59 UTC, merged