Add info on TO keyword
JupiterOne/docs pull request #183
Opened 2021-02-27 21:20 UTC by jayson-jensen-pro

2021-03-01 17:08 UTC, jayson-jensen-pro commented
Need to provide a link to https://github.com/JupiterOne/docs/pull/169/files once the PR is merged.

2021-03-01 22:13 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +> **Exception**: For the relationship verb `RELATES TO`, both words must be used
Move the exception information to the top - "Except in the case of `RELATES TO`, `TO` is considered a filler word that can be use after a relationship verb." something like that.

2021-03-02 18:54 UTC, a-u-h-g requested changes

2021-03-02 18:54 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +*See the J1QL tips and tricks guide (insert link here) for more info on the usage of `RELATES TO`.*
just remove this line - there isn't really a section on `RELATES TO` in that article, and there is no link yet. If you want you could add more details on `RELATES TO` above in this article.

2021-03-02 19:23 UTC, jayson-jensen-pro commented on docs/jupiterone-query-language.md
> +*See the J1QL tips and tricks guide (insert link here) for more info on the usage of `RELATES TO`.*
I went ahead and removed the line. Was thinking a section on relationship verbs could be a good task for a future sprint. LMK your thoughts and I can add.

2021-03-02 21:18 UTC, a-u-h-g requested changes

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +is considered a 'filler' word that is ignored by the query
```suggestion
is considered a 'filler' word that is ignored by the interpreter
```

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +> The keyword `to` is supported by J1QL so that the query can be read as a
```suggestion
> The keyword `TO` is supported in J1QL so that the query can be read as a
```

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +> natural language question. Although `to` can be used in a query, if omitted,
```suggestion
> natural language question. Although `TO` can be used in a query, if omitted,
```

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +> The following are some example relationship verbs where `to` could be used:\
```suggestion
> The following are some example relationship verbs where `TO` could be used:
```

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +> deployed to
A bulleted list of code here with all caps would be better

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +> FIND User that contributes to CodeRepo
```suggestion
> FIND User THAT CONTRIBUTES TO CodeRepo
```

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +> FIND User that contributes CodeRepo
```suggestion
> FIND User THAT CONTRIBUTES CodeRepo
```

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
> +> The following queries will return the same result:\
```suggestion
> The following queries will return the same result:
```

2021-03-02 21:18 UTC, a-u-h-g commented on docs/jupiterone-query-language.md
>  Keep in mind the keywords are _case insensitive_.
```suggestion
**Reminder** J1QL keywords are not case sensitive.
```

2021-03-02 23:53 UTC, a-u-h-g approved these changes

2021-03-03 00:34 UTC, merged