first draft of GRC data model narrative
JupiterOne/docs pull request #186
Opened 2021-03-02 21:27 UTC by tanggk

first draft of GRC data model narrative

2021-03-02 21:29 UTC, tanggk commented
![Screen Shot 2021-03-02 at 1 28 49 PM](https://user-images.githubusercontent.com/29790705/109717694-42546680-7b5b-11eb-9bc6-a9057b73dc1b.png)
^this is what I see in VS Code for both the actual markdown + the rendering previewer

2021-03-02 22:17 UTC, a-u-h-g commented on docs/data-model/org-grc.md
> +**Procedures** are written security documents which describe how to implement
would also mention how procedures relate to requirements

2021-03-02 22:17 UTC, a-u-h-g commented on docs/data-model/org-grc.md
> +<iframe src="https://my.mindnode.com/2ayndotqvjEJ3qAeEfwyy6sgkRciyxRvH1sgpYw4/em#166,242,-3" frameborder="0" marginheight="0" marginwidth="0" style="border: 1px solid rgb(204, 204, 204); width: 720px
```suggestion
<iframe src="https://my.mindnode.com/2ayndotqvjEJ3qAeEfwyy6sgkRciyxRvH1sgpYw4/em#333.4,207.2,-2" frameborder="0" marginheight="0" marginwidth="0" style="border: 1px solid rgb(204, 204, 204); width: 720px; height: 720px;" onmousewheel=""></iframe>
```

2021-03-02 22:17 UTC, a-u-h-g commented on docs/data-model/org-grc.md
> +Vendors are frequently companies, organizations, or people.
```suggestion
**Vendors** are frequently companies, organizations, or people. 
```

2021-03-02 22:17 UTC, a-u-h-g commented on docs/data-model/org-grc.md
> +Vendors are frequently companies, organizations, or people.
would also mention how `Vendors` can `PROVIDE` a `Control` to give context for the continued examples after

2021-03-02 22:17 UTC, a-u-h-g commented on docs/data-model/org-grc.md
> +### Roughly, you can almost think of an organization’s policies, procedures, and controls to loosely align to the compliance or regulatory standards, sections, and requirements.
This seems too long and casual a statement for a heading. You could be better off having two H2 headings one for `## Standards, Sections, and Requirements` at the top, and one for `## Policies, Procedures, Controls, and Configurations` here. You can then put this sentence in bold immediately under the heading. You could also use H3 for all the Classes that you currently have in bold.

2021-03-02 22:43 UTC, tanggk commented on docs/data-model/org-grc.md
> +Vendors are frequently companies, organizations, or people.
I updated

2021-03-02 22:44 UTC, tanggk commented on docs/data-model/org-grc.md
> +### Roughly, you can almost think of an organization’s policies, procedures, and controls to loosely align to the compliance or regulatory standards, sections, and requirements.
I updated

2021-03-08 23:09 UTC, erkangz requested changes

2021-03-08 23:09 UTC, erkangz commented on docs/data-model/org-grc.md
> +> **control**.
```suggestion
> A `ControlPolicy` or `Configuration` _enforces_ or _manages_ a
> `Control`.
```

2021-03-08 23:09 UTC, erkangz commented on docs/data-model/org-grc.md
> +    Examples of controls include: password settings, data encryption at rest or in transit,  and pre-employment background checks.
```suggestion
Examples of controls include: 

- user identity management, access control, multi-factor authentication
- data encryption at rest or in transit
- penetration testing, code scanning
- pre-employment background checks.
```

2021-03-08 23:09 UTC, erkangz commented on docs/data-model/org-grc.md
> +    Examples of vendors include Microsoft Active Directory’s (AD) Group Policy Objects (GPO) for password requirements, Amazon Web Services’ (AWS) Key Management Service (KMS) for encryption at rest,
```suggestion
Examples of vendors include:

- Microsoft (the Vendor) for Active Directory (AD), user authentication, and access control
- Amazon Web Services (AWS, the Vendor) for Key Management Service (KMS)
- Checkr (the Vendor) for background screens
```

2021-03-08 23:09 UTC, erkangz commented on docs/data-model/org-grc.md
> +    Examples of control policies or configurations include: requiring 12+ characters including a number + a symbol for all passwords, using AES-256 cipher for encryption at rest, and for background c
```suggestion
Examples of control policies or configurations include: 

- requiring 12+ characters including a number + a symbol for all passwords
- using AES-256 cipher for encryption at rest
- for background checks, specifically include searches for federal, criminal, state, county, city, financial, and education verification
```

2021-03-08 23:09 UTC, erkangz commented on docs/data-model/org-grc.md
> +    Examples of procedures include procedures around: password management, protecting data at rest, and employee screening.
```suggestion
Examples of procedures (aka control/process descriptions) include: 

- password management
- protecting data at rest 
- employee screening
```

2021-03-09 14:46 UTC, tanggk commented on docs/data-model/org-grc.md
> +
do you mean we need to build these 2x new data types/entities into the GRC model in the future? I'm not sure I follow 100%

2021-03-17 21:55 UTC, tanggk commented on docs/data-model/org-grc.md
> +
domains + controls can be defined by a standard, e.g., CIS; J1 has 22 domains + 100+ controls via P+P. CIS has 20 domains 127 controls

domain/controls can be defined by industry standards, or P+P defined by J1/your org.

2021-03-23 21:23 UTC, tanggk commented on docs/data-model/org-grc.md
> +
updated per comments

2021-03-24 21:44 UTC, erkangz approved these changes

2021-03-24 21:44 UTC, merged