Release 66
JupiterOne/docs pull request #197
Opened 2021-03-11 21:57 UTC by erkangz

2021-03-11 22:03 UTC, ndowmon commented on release-notes/2021-66.md
> +    (3.8/3.7)
See https://bitbucket.org/jupiterone/jupiter-integration-azure/pull-requests/132/add-azure-cis-benchmark-36-39

```suggestion
  - Are all Azure storage accounts configured with "Deny" as the default network
    access rule? (3.7/3.6)
  - Are "Trusted Microsoft Services" enabled for Azure storage accounts?
    (3.8/3.7)
  - Is "Soft Delete" enabled for Azure storage accounts?
    (na/3.8)
  - Are Azure storage accounts encrypted with Customer Managed Keys?
    (na/3.9)
```

2021-03-11 23:31 UTC, alee-j1 commented on docs/integrations/rapid7/index.md
>  ## Data Model
This could also be removed since there's another "Data Model" heading below

2021-03-11 23:32 UTC, alee-j1 requested changes
just one comment for the rapid 7 docs page for the duplicate "Data Model" heading

2021-03-12 13:46 UTC, henrymgarrett approved these changes

2021-03-12 15:03 UTC, austinkelleher requested changes

2021-03-12 15:03 UTC, austinkelleher commented on release-notes/2021-66.md
> +- Migrated integration to latest SDK and infrastructure for more reliable execution
This looks like copy/paste. Google Cloud has always been on the new SDK. However, GCP did add the following:

```
- Support for ingesting the following **new** resources

- New relationships

  - GKE
    - `google_container_node_pool` **HAS** `google_compute_instance_group`

- New properties added to resources:
  - GKE
    - `google_container_node_pool`
      - `serviceAccount`
      - `bootDiskKmsKey`
  - `google_container_cluster`
    - `workloadIdentity`
```

2021-03-12 15:11 UTC, aiwilliams commented on release-notes/2021-66.md
> +- Migrated integration to latest SDK and infrastructure for more reliable execution
It was meant to capture the move to ECS to allow the integration to complete. That was done this past sprint in https://bitbucket.org/jupiterone/jupiter-integration-google-cloud/pull-requests/26.

Thanks for catching the missing new resources!

2021-03-12 19:35 UTC, erkangz commented
Good to go

2021-03-15 14:13 UTC, merged