Add rca 20210309
JupiterOne/docs pull request #198
Opened 2021-03-12 19:55 UTC by a-u-h-g

Creating a public docs folder for our RCAs to share with customers, including the RCA from 2021-03-09, removed internal links/references

2021-03-15 16:27 UTC, charlieduong94 commented
Nice, thanks for cleaning up the internal doc!

2021-03-15 16:28 UTC, charlieduong94 approved these changes

2021-03-16 16:57 UTC, erkangz requested changes

2021-03-16 16:57 UTC, erkangz commented on rcas/20210309-cognito-outage.md
> +JuipterOne could not provide a workaround withing the timespan of this outage,
```suggestion
JupiterOne could not provide a workaround within the timespan of this outage,
```

2021-03-16 16:57 UTC, erkangz commented on rcas/20210309-cognito-outage.md
> +    issued by JuipterOne's `token-service`. This flow avoids the additional calls to Cognito JKWS.
```suggestion
    issued by JupiterOne's `token-service`. This flow avoids the additional calls to Cognito JKWS.
```

2021-03-16 19:42 UTC, aiwilliams approved these changes
Nothing significant to contribute, but thought I might add some grammar suggestions that jumped out at me.

2021-03-16 19:42 UTC, aiwilliams commented on rcas/20210309-cognito-outage.md
> +        to access J1 APIs via API keys.
```suggestion
    -   Customers reported their automations broken because they were unable
        to access J1 APIs via API keys.
```

2021-03-16 19:42 UTC, aiwilliams commented on rcas/20210309-cognito-outage.md
> +    -   There was not significant action that could be taken to rectify the issue faster.
```suggestion
    -   No significant action could be taken by JupiterOne to reduce time to recovery.
```

2021-03-16 19:42 UTC, aiwilliams commented on rcas/20210309-cognito-outage.md
> +        working state within an hour.
```suggestion
    -   AWS acknowledged the Cognito service disruption in a timely manner and restored all
        service capabilities within an hour.
```

2021-03-16 19:42 UTC, aiwilliams commented on rcas/20210309-cognito-outage.md
> +        the same time JupiterOne employees and customers noticed the issue.
The document refers to our team as `JupiterOne` elsewhere.
```suggestion
    -   Internal JupiterOne monitoring services provided early identification of the issue,
        just ahead of reports from employees and customers.
```

2021-03-16 22:03 UTC, erkangz approved these changes

2021-03-16 22:17 UTC, merged