Add Trigger Integration Job via API
JupiterOne/docs pull request #209
Opened 2021-03-23 17:50 UTC by jayson-jensen-pro

Could you review how we want to call out the api request? I wasn't sure if we wanted to try and stay consistent in our examples or if we had to use Curl.

2021-03-23 18:17 UTC, a-u-h-g commented on docs/jupiterone-api.md
> +  "query":"mutation Invoke {\n  invokeIntegrationInstance(id: \"{INTEGRATION_INSTANCE_ID}\") {\n    success\n  }\n}\n"
replace the line break characters with actual line breaks

2021-03-23 18:20 UTC, a-u-h-g commented on docs/jupiterone-api.md
>  ## Example Usage
```suggestion
## Additional API Examples
```
Sidenoet: let's also change this header because "Example Usage" is vague following this integration API

2021-03-23 18:24 UTC, a-u-h-g commented
Couple comments, but definitely best this way instead of curl example

2021-03-23 19:20 UTC, a-u-h-g commented on docs/jupiterone-api.md
> +    invokeIntegrationInstance(id: \"{INTEGRATION_INSTANCE_ID}\") {
You won't need the escape characters `\` in a typical api call, they were specific to the curl script example

2021-03-23 19:22 UTC, a-u-h-g commented on docs/jupiterone-api.md
> +      success
this "success" looks odd - please request Issac as a reviewer for final look.

2021-03-23 19:23 UTC, a-u-h-g commented on docs/jupiterone-api.md
> +      success
to clarify, it should be correct, but worth getting him as a reviewer anyway.

2021-03-23 19:41 UTC, jayson-jensen-pro commented on docs/jupiterone-api.md
> +      success
For sure. I have Issac included as a reviewer. @fomentia could you review the query and api request?

2021-03-23 19:56 UTC, a-u-h-g commented on docs/jupiterone-api.md
> +    invokeIntegrationInstance(id: {INTEGRATION_INSTANCE_ID}) {
```suggestion
    invokeIntegrationInstance(id: "{INTEGRATION_INSTANCE_ID}") {
```

2021-03-24 13:47 UTC, fomentia requested changes

2021-03-24 13:47 UTC, fomentia commented on docs/jupiterone-api.md
> +`INTEGRATION_INSTANCE_ID` - This value is the ID of the specific integration job
```suggestion
`INTEGRATION_INSTANCE_ID` - This value is the ID of the specific integration instance
```

2021-03-24 13:47 UTC, fomentia commented on docs/jupiterone-api.md
> +      success
If this is JSON (the format, not the person lol), then this will fail as the double-quotes around the integration instance ID are not escaped.

And yes, `success` is correct. It is the only property on the invocation result and it is a boolean.

2021-03-24 16:45 UTC, a-u-h-g commented on docs/jupiterone-api.md
> +      success
Ah I miss read it, thanks

2021-03-24 17:51 UTC, fomentia approved these changes

2021-03-24 18:08 UTC, merged