Create 2021-69.md
JupiterOne/docs pull request #225
Opened 2021-04-19 21:51 UTC by billfox1

Sprint 69 Release Notes

Erkang: I've rec'd Adam and Carter's notes, not sure if Phil has any, but here is the initial PR...

2021-04-20 17:17 UTC, aiwilliams submitted a review, later dismissed
Seems good to me. 👍

2021-04-21 17:48 UTC, erkangz requested changes

2021-04-21 17:48 UTC, erkangz commented on release-notes/2021-69.md
> +  - `tags`: Simple Qualys asset tag values (i.e. `tags: ["Cloud Agent"]`)
same here. space/empty line before and after. please fix other places too

2021-04-21 17:48 UTC, erkangz commented on release-notes/2021-69.md
> +  |                       | `google_spanner_instance_config`                              |
space empty line needed

2021-04-21 17:48 UTC, erkangz commented on release-notes/2021-69.md
> +- Added support for ingesting the following **new** resources:
Space/empty line after

2021-04-21 17:48 UTC, erkangz commented on release-notes/2021-69.md
> +  [docs](https://github.com/JupiterOne/graph-cobalt/blob/master/docs/jupiterone.md)
we need to copy and publish the Cobalt integration doc into the docs repo, and use relative link here:

```
[docs](../docs/integrations/cobalt/index.md)
```

2021-04-21 17:48 UTC, erkangz commented on release-notes/2021-69.md
> +- Added support for ingesting the following **new** resources:
space empty line needed before and after the table

2021-04-21 17:49 UTC, erkangz commented on release-notes/2021-69.md
> +- Updated all existing procedures to have considerations if there are considerations matching the templates found in GitHub
```suggestion
- Display "considerations" when available, in the editing view of a procedure in the Policies app. 
  Also updated all existing procedures to have considerations if available from the templates.
```

2021-04-21 18:10 UTC, billfox1 commented on release-notes/2021-69.md
> +  [docs](https://github.com/JupiterOne/graph-cobalt/blob/master/docs/jupiterone.md)
Replace line 46 link with the ../docs/integrations/cobalt/index.md?  Would you ping me the entire url when you get a chance?

2021-04-21 20:00 UTC, erkangz approved these changes

2021-04-21 20:01 UTC, merged