Update iam responses for queries and mutations
JupiterOne/docs pull request #253
Opened 2021-05-24 14:13 UTC by harlowk

- Both mutations resolve to { success }
- Added all properties exposed by query results.

2021-05-24 14:34 UTC, a-u-h-g approved these changes
thanks for the update!

2021-05-24 14:36 UTC, fomentia commented
Also note, we don't need to use `https://api.us.jupiterone.io/iam/graphql` anymore since I fixed the service to be compatible with the proxy (all calls can be made using `https://api.us.jupiterone.io/graphql`).

2021-05-24 14:41 UTC, philidem requested changes

2021-05-24 14:41 UTC, philidem commented on docs/jupiterone-api.md
> +      type
I intentionally removed `type` and `description` from the docs because we aren't using them. These properties are non-essential so I don't think we should include them in the API and docs.

2021-05-24 14:41 UTC, philidem commented on docs/jupiterone-api.md
> +      id
Please change this to `userId` in the IAM service. I would just omit `id` from the docs for now.

2021-05-24 14:45 UTC, fomentia commented on docs/jupiterone-api.md
> +      id
I'm not sure that this should be `userId`. It's a property on the `User` type.

2021-05-24 14:50 UTC, philidem commented on docs/jupiterone-api.md
> +	  "description": "Group for users"
This is not aligned properly

2021-05-24 18:32 UTC, harlowk commented on docs/jupiterone-api.md
> +      id
The response for IamGroupUsers is a PagedUserResponse, where items: User[] and User is { id: string, email: string }

2021-05-26 23:05 UTC, harlowk commented
Bump! Waiting approval; all comments should be resolved. @philidem @fomentia

2021-05-27 12:35 UTC, fomentia commented on docs/jupiterone-api.md
> +**Mutation: addIamUserToGroupByEmail** creates or updates a group membership.
Minor: I don't think this mutation will ever "update" a membership

2021-05-27 12:35 UTC, fomentia approved these changes

2021-07-30 20:53 UTC, closed without merging