Ab#5498 add compliance api endpoints
JupiterOne/docs pull request #256
Opened 2021-05-27 13:58 UTC by jayson-jensen-pro

2021-05-27 14:30 UTC, austinkelleher requested changes
Thanks for doing this 🙏

2021-05-27 14:30 UTC, austinkelleher commented on docs/jupiterone-compliance-api.md
> +    complianceStandards(size: $size, cursor: $cursor) {
Seems like there are some issues with spacing in each of these

2021-05-27 14:32 UTC, austinkelleher commented on docs/jupiterone-compliance-api.md
> +    complianceStandards(size: $size, cursor: $cursor) {
You can use this for formatting: https://crubier.github.io/graphql-code-pretty-printer/

2021-05-28 15:47 UTC, hesto2 approved these changes
Looks good to me 🎉 I can't verify every field/variable for all of the queries, but at a high level this looks correct to me

2021-05-28 19:12 UTC, jayson-jensen-pro commented on docs/jupiterone-compliance-api.md
> +    complianceStandards(size: $size, cursor: $cursor) {
Done, thanks for the resource!

2021-05-28 19:33 UTC, a-u-h-g approved these changes

2021-05-28 19:50 UTC, austinkelleher approved these changes

2021-05-28 19:51 UTC, merged