Added the Salesforce docs
JupiterOne/docs pull request #272
Opened 2021-06-30 19:44 UTC by ceelias

2021-06-30 21:49 UTC, aiwilliams requested changes
I submitted questions about the generated relationships, would love to hear your thoughts on whether we can use `ASSIGNED` for some of them.

2021-06-30 21:49 UTC, aiwilliams commented on docs/integrations/salesforce/index.md
> +  configured to allow for this flow.
Is it required that the person installing the connected app into the Salesforce org have a certain level of access? It may be helpful to indicate that here.
```suggestion
- JupiterOne is a Salesforce Connected App that will require a user authorized to
grant access to your Salesforce org’s data.
```

2021-06-30 21:49 UTC, aiwilliams commented on docs/integrations/salesforce/index.md
> +| GROUP         | `salesforce_group`          | `Group`         |
Why is this `GROUP` instead of simply `Group`?

2021-06-30 21:49 UTC, aiwilliams commented on docs/integrations/salesforce/index.md
> +| `salesforce_user`      | **HAS**               | `salesforce_user_role`      |
Could this be `ASSIGNED`?

2021-06-30 21:49 UTC, aiwilliams commented on docs/integrations/salesforce/index.md
> +| `salesforce_user`      | **HAS**               | `salesforce_permission_set` |
Could these be `ASSIGNED`?

2021-06-30 21:49 UTC, aiwilliams commented on docs/integrations/salesforce/index.md
> +| `salesforce_user_role` | **HAS**               | `salesforce_user_role`      |
I don't recall seeing a model before where a role is related to a role. What is the use case in Salesforce for this?

2021-07-01 01:19 UTC, ceelias commented on docs/integrations/salesforce/index.md
> +| `salesforce_user_role` | **HAS**               | `salesforce_user_role`      |
I thought it was weird as well, but if you look at their data model they have roles of roles.

Data model: https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_erd_users.htm

Role Hierarchy: https://www.tutorialspoint.com/salesforce/salesforce_create_a_role_hierarchy.htm

2021-07-01 15:53 UTC, aiwilliams commented on docs/integrations/salesforce/index.md
> +| `salesforce_user_role` | **HAS**               | `salesforce_user_role`      |
Thanks for those links, very helpful. I bumped around in their UI for adding a User and learned more about these "role hierarchies".

![Screen Shot 2021-07-01 at 11 47 03 AM](https://user-images.githubusercontent.com/2571/124153120-18a44100-da62-11eb-94d8-1c9e5d9199c0.png)

@JupiterOne/integrations, what do you think of [using `CONTAINS` as the relationship class](https://github.com/JupiterOne/data-model/blob/7f861059bb8b19db851bf5ad0753d798e3da432b/src/RelationshipClass.ts#L43) (compare to [`HAS`](https://github.com/JupiterOne/data-model/blob/7f861059bb8b19db851bf5ad0753d798e3da432b/src/RelationshipClass.ts#L93))? The hierarchy does not allow a role to be possessed by more than one other role.

I'm thinking that `FIND Role THAT CONTAINS Role` makes more sense than `FIND Role THAT HAS Role` because it more clearly captures the fact that a role lower in the hierarchy does not have the access than the roles that contain it.

2021-07-01 16:05 UTC, aiwilliams commented on docs/integrations/salesforce/index.md
> +| `salesforce_user_role` | **HAS**               | `salesforce_user_role`      |
Created https://github.com/JupiterOne/data-model/pull/110 to drive toward clarity.

2021-07-06 21:12 UTC, a-u-h-g submitted a review, later dismissed

2021-07-06 21:13 UTC, a-u-h-g commented
Approved, Only question is if"
`| `salesforce_group`     | **HAS**               | `salesforce_user_role`      |`
should be an `ASSIGNED` relationship

2021-07-08 13:29 UTC, aiwilliams approved these changes
Thanks for fixing these things up!

2021-07-08 21:15 UTC, merged