Janettelynch patch 3
JupiterOne/docs pull request #347
Opened 2021-08-31 18:36 UTC by janettelynch

DOC-7 updates to the Asset filters topic for critical assets.

2021-09-02 20:17 UTC, benrj requested changes
Looks good - just a couple image URL references that need fixing

2021-09-02 20:17 UTC, benrj commented on JupiterOne User Documentation Process.md
> +1. If you need user documentation, in the epic Jira ticket, click Yes in the Documentation Required? field.
```suggestion
1. If you need user documentation, in the epic Jira ticket, click Yes in the `Documentation Required?` field.
```

2021-09-02 20:17 UTC, benrj commented on guides/asset-inventory-filters.md
> +Click ![](C:\Users\lynch\Documents\GitHub\docs\assets\icons\gear.png)to edit the critical asset definition default values. You can use classes, properties, and values
this will need to be relative to this file... so something like `../assets/icons/gear.png`?

2021-09-02 20:17 UTC, benrj commented on guides/asset-inventory-filters.md
> +![](C:\Users\lynch\Documents\GitHub\docs\assets\asset-definition.png)
same here

2021-09-07 17:13 UTC, AnneNielsenJ1 commented on Glossary of Terms.md
> +| Class             | The class of an entity is an abstract label that defines what the entity is within the concept of security operations. |
@janettelynch could we add a couple of examples to make this clear what a class is vs what it is not? @charlieduong94 would the best person to provide such examples.

2021-09-08 17:40 UTC, charlieduong94 commented on Glossary of Terms.md
> +| Class             | The class of an entity is an abstract label that defines what the entity is within the concept of security operations. |
What we have in the data model [here](https://github.com/JupiterOne/data-model/tree/main/src/schemas) are classes that can be used as an example. Might be helpful to call out that they use pascal case (upper camel case). `User`, `AccessPolicy`, and `NetworkInterface` would probably be good examples to use.

Also, for the description of `Type` (below), those values are snake case. `jupiterone_user`, `aws_iam_policy` and `aws_eni` are examples of types that would typically be paired with the classes I've listed above. Hope that's helpful!

2021-09-08 19:28 UTC, benrj commented on Glossary of Terms.md
> +|                   |                                                              |
It looks like these were here before, but wondering if we can get rid of all these extra rows?

2021-09-08 19:28 UTC, benrj submitted a review, later dismissed

2021-09-08 20:03 UTC, charlieduong94 approved these changes

2021-09-08 20:20 UTC, charlieduong94 requested changes

2021-09-08 20:20 UTC, charlieduong94 commented on Glossary of Terms.md
> +| Entity            | (Capitalized? I have seen it both ways) Digital assets in your environment. |
oof actually this seems weird `(Capitalized? I have seen it both ways)`

2021-09-09 16:13 UTC, AnneNielsenJ1 submitted a review, later dismissed

2021-09-09 19:16 UTC, janettelynch commented on Glossary of Terms.md
> +| Entity            | (Capitalized? I have seen it both ways) Digital assets in your environment. |
I will cover this in a future PR.

2021-09-09 19:16 UTC, janettelynch commented on Glossary of Terms.md
> +| Exception         | Outlier circumstance.                                        |
I will cover this in a future PR.

2021-09-09 19:22 UTC, charlieduong94 approved these changes

2021-09-09 19:24 UTC, merged