Release Notes 2021-79
JupiterOne/docs pull request #351
Opened 2021-09-08 22:12 UTC by janettelynch

2021-09-09 12:29 UTC, AnneNielsenJ1 submitted a review, later dismissed

2021-09-09 14:44 UTC, billfox1 approved these changes

2021-09-09 16:09 UTC, AnneNielsenJ1 approved these changes

2021-09-09 16:45 UTC, AnneNielsenJ1 approved these changes

2021-09-09 17:18 UTC, erkangz requested changes

2021-09-09 17:18 UTC, erkangz commented on release-notes/2021-79.md
> +  of double arrows,`<<` and `>>`.
we should provide a quick example here and add link to the docs

2021-09-09 17:18 UTC, erkangz commented on release-notes/2021-79.md
> +- Improved messaging when bulk synchronization fails.
```suggestion
- Improved error messages when a bulk synchronization fails.
```

Is this error message in the UI or API? Please add to clarify

2021-09-09 17:18 UTC, erkangz commented on release-notes/2021-79.md
> +  Learn more about how to customize and use critical assets [here](https://github.com/JupiterOne/docs/blob/main/guides/asset-inventory-filters.md).
This description can be improved to be more compelling and better describe the "critical assets" feature. 

Also the link needs to be relative path, not a static link to the file on github, otherwise it won't be parsed correctly when published.

```
[here](../guides/asset-inventory-filters.md)
```

That said, the `asset-inventory-filters.md` file does NOT describe how to configure critical assets. Do we have a separate doc for it?

2021-09-09 17:19 UTC, erkangz commented
@AnneNielsenJ1 @janettelynch we should also include content updates. For example, new widgets added to S3 Insights dashboard, new compliance standards added (if any), etc.

2021-09-09 19:20 UTC, janettelynch commented on release-notes/2021-79.md
> +  of double arrows,`<<` and `>>`.
@erkangz Can you review my added example and let me know if it is valid?

2021-09-09 19:25 UTC, janettelynch commented on release-notes/2021-79.md
> +  Learn more about how to customize and use critical assets [here](https://github.com/JupiterOne/docs/blob/main/guides/asset-inventory-filters.md).
@erkangz The PR https://github.com/JupiterOne/docs/pull/347 for the new doc is merged. So, it just has to be published to zendesk.

2021-09-09 19:37 UTC, AnneNielsenJ1 commented on release-notes/2021-79.md
> +  Learn more about how to customize and use critical assets [here](https://github.com/JupiterOne/docs/blob/main/guides/asset-inventory-filters.md).
@erkangz @janettelynch what about:

Introduced a new quick filter for accessing critical assets in the Assets app. 

Critical assets provides a shortcut for you to more easily monitor important changes in your cloud environment and receive alerts for new issues such as security findings or changes in access controls around your critical assets. This allows you to quickly focus on and resolve the most important issues. 

Learn more about how to customize and configure your critical assets here: LINK

2021-09-09 19:46 UTC, tywalch submitted a review, later dismissed

2021-09-10 00:28 UTC, AnneNielsenJ1 submitted a review, later dismissed

2021-09-10 00:32 UTC, AnneNielsenJ1 commented on release-notes/2021-79.md
> +- Improved messaging when bulk synchronization fails.
This an error message in the UI.

2021-09-10 14:05 UTC, erkangz requested changes

2021-09-10 14:05 UTC, erkangz commented on release-notes/2021-79.md
> +  This allows you to quickly focus on and resolve your most important security issues.
```suggestion
    Critical Assets are defined using a preset combination of entities classes and attributes 
    (e.g. Hosts and Applications tagged as production). This configuration can be easily customized
    to match your specific definition of what critical assets mean for your organization.
    
    Learn more about how to customize and configure your critical assets 
    [here](../guides/critical-assets.md).
    
    Critical Assets can be reference in query via a specific "Smart Class" shorthand: `#CriticalAsset`. 
    
    This allows you to easily query and monitor important changes and receive alerts when a drift or
    problem occurs for any of the critical assets you care about. It allows you to focus and prioritize 
    on the most important risks.
    
    For example, to identify and alert on new critical assets added in the last 24 hours:
    
    `Find #CriticalAsset with _createdOn > date.now - 24hours`
    
    This is the initial release of this capability. We will be adding some pre-built alert rules and Insights
    dashboards for critical assets soon.
```

2021-09-10 14:05 UTC, erkangz commented on release-notes/2021-79.md
> +  Learn more about how to customize and configure your critical assets [here](../guides/asset-inventory-filters.md).
this can be deleted if we use the suggestion above.

2021-09-10 14:05 UTC, erkangz commented on release-notes/2021-79.md
> +- Introduced a new quick filter for accessing critical assets in the Assets app.
```suggestion
- Introduced a new filter to define **Critical Assets** in the Assets app, 
  and a **Smart Class** query shorthand.
```

2021-09-10 15:58 UTC, erkangz approved these changes

2021-09-10 16:00 UTC, merged