2021 83 Release Notes
JupiterOne/docs pull request #404
Opened 2021-11-03 18:30 UTC by janettelynch

Please review and edit.

2021-11-04 19:27 UTC, AnneNielsenJ1 commented
@janettelynch I made a few changes, can you re-read to make sure this is still in proper english?

2021-11-04 19:28 UTC, AnneNielsenJ1 commented
@ninetreats can you review the changes I made and make sure this is still accurate?

2021-11-04 19:45 UTC, ninetreats commented on release-notes/2021-83.md
> +- Entites in the Graph Viewer that have a *problem* associated with them now have a visual idication and details of the problem
spelling error - "idication"

2021-11-04 19:46 UTC, ninetreats commented on release-notes/2021-83.md
> +- The Center for Internet Security (CIS)) Controls Version 8 is now available as a standard in the
extra close parens (CIS))

2021-11-04 19:47 UTC, ninetreats commented on release-notes/2021-83.md
> +  Compliance with [the mapped controls](../guides/compliance/compliance-mapping-policies.md) to the default procedures
Is there a word missing here? "...in the Compliance with..."

2021-11-04 19:51 UTC, ninetreats requested changes
@AnneNielsenJ1 I added a couple comments.  Found some small typos and maybe a missing word.

2021-11-05 13:53 UTC, austinkelleher commented
Additional integration release notes @janettelynch @ninetreats :

```md
## Integrations

### Azure

-   Added support for ingesting the following **new** resources:

| Resources                | Entity `_type`             | Entity `_class` |
| ------------------------ | -------------------------- | --------------- |
| Azure Kubernetes Cluster | `azure_kubernetes_cluster` | `Cluster`       |
| Resource Lock            | `azure_resource_lock`      | `Rule`          |
| Key Vault Key            | `azure_keyvault_key`       | `Key`           |
| Key Vault Secret         | `azure_keyvault_secret`    | `Secret`        |

-   Added support for ingesting the following **new** relationships:

| Source Entity `_type`  | Relationship `_class` | Target Entity `_type`      |
| ---------------------- | --------------------- | -------------------------- |
| `azure_resource_group` | **HAS**               | `azure_kubernetes_cluster` |
| `azure_resource_lock`  | **HAS**               | `ANY_SCOPE`                |

-   New properties added to resources:

    | Entity                   | Properties                                                                                                    |
    | ------------------------ | ------------------------------------------------------------------------------------------------------------- |
    | `azure_keyvault_service` | `enableSoftDelete`, `enablePurgeProtection`                                                                   |
    | `azure_storage_account`  | `tableAnalyticsLoggingReadEnabled`, `tableAnalyticsLoggingWriteEnabled`, `tableAnalyticsLoggingDeleteEnabled` |

#### JupiterOne Questions Added

> Are all critical resources protected by resource locks?
> Are all Key Vaults recoverable?
> Is RBAC enabled on all Azure Kubernetes Services Instances?

### GitHub

-   When a JupiterOne GitHub application installation does not have permission to fetch two factor authentication information for `github_user`s, the `github_user` `mfaEnabled` property will now be assigned `undefined` instead of `false`

### Knowbe4

-   Added support for ingesting the following **new** resources:

| Resources                      | Entity `_type`                   | Entity `_class` |
| ------------------------------ | -------------------------------- | --------------- |
| KnowBe4 Phishing Campaign      | `knowbe4_phishing_campaign`      | `Training`      |
| KnowBe4 Phishing Security Test | `knowbe4_phishing_security_test` | `Assessment`    |

-   Added support for ingesting the following **new** relationships:

| Source Entity `_type`       | Relationship `_class` | Target Entity `_type`            |
| --------------------------- | --------------------- | -------------------------------- |
| `knowbe4_account`           | **HAS**               | `knowbe4_phishing_campaign`      |
| `knowbe4_account`           | **HAS**               | `training_campaign`              |
| `knowbe4_phishing_campaign` | **CONTAINS**          | `knowbe4_phishing_security_test` |

### Kubernetes

-   Added support for ingesting the following **new** resources:

| Resources                            | Entity `_type`                   | Entity `_class` |
| ------------------------------------ | -------------------------------- | --------------- |
| Kubernetes Cluster                   | `kube_cluster`                   | `Cluster`       |
| KnowBe4 Phishing Security Test       | `knowbe4_phishing_security_test` | `Assessment`    |
| Kubernetes Container Spec            | `kube_container_spec`            | `Configuration` |
| Kubernetes Pod Security Policy (PSP) | `kube_pod_security_policy`       | `Configuration` |
| Kubernetes Network Policy            | `kube_network_policy`            | `Configuration` |

-   Added support for ingesting the following **new** relationships:

| Source Entity `_type` | Relationship `_class` | Target Entity `_type`      |
| --------------------- | --------------------- | -------------------------- |
| `kube_cluster`        | **CONTAINS**          | `kube_namespace`           |
| `kube_deployment`     | **USES**              | `kube_container_spec`      |
| `kube_cluster`        | **CONTAINS**          | `kube_pod_security_policy` |
| `kube_namespace`      | **CONTAINS**          | `kube_network_policy`      |

#### JupiterOne Questions Added

> Which Kubernetes container specs admit containers to run in privileged mode?
> Which Kubernetes containers are permitted to run as the root user?
> Which Kubernetes Pod Security Policies (PSP) admit privileged containers?
> Which Kubernetes Pod Security Policies (PSP) admit containers to share the host process ID namespace?
> Which Kubernetes Pod Security Policies (PSP) admit containers to share the host IPC namespace?
> Which Kubernetes Pod Security Policies (PSP) admit containers to share the host network namespace?
> Which Kubernetes Pod Security Policies (PSP) admit containers to escalate privileges?
> Which Kubernetes Pod Security Policies (PSP) admit containers with the NET_RAW capability?
> Which Kubernetes Pod Security Policies (PSP) admit containers with the added capabilities?
> Which Kubernetes namespaces do not have network policies defined?

### Qualys

-   Qualys web application scan ingestion is now able to be enabled/disabled based on the integration configuration. A new "Ingest Web App Scans" integration configuration option has been introduced, and the option can be toggled from the JupiterOne Qualys integration configuration page
```

2021-11-05 14:18 UTC, austinkelleher commented
Additionally, under the "Qualys" section:

```
- JupiterOne now fetches Qualys findings (`qualys_host_finding`) with status "Fixed"
```

2021-11-05 19:05 UTC, AnneNielsenJ1 approved these changes

2021-11-05 19:07 UTC, AnneNielsenJ1 approved these changes

2021-11-08 14:19 UTC, merged