Create 2021.86
JupiterOne/docs pull request #434
Opened 2021-12-11 21:07 UTC by AnneNielsenJ1

Release note for s3 bucket changes

2021-12-14 22:54 UTC, ninetreats reviewed
@aiwilliams @austinkelleher I've added release notes for all the integrations since the release notes.

2021-12-15 16:45 UTC, janettelynch submitted a review, later dismissed

2021-12-15 20:05 UTC, erkangz requested changes

2021-12-15 20:05 UTC, erkangz commented on release-notes/2021-86.md
> +- Account administrations can now parameterize sensitive values such as secrets for use in J1QL queries and questions without exposing the values.
`Account administrators`?

2021-12-15 20:05 UTC, erkangz commented on release-notes/2021-86.md
> +- Vendor data in the public [vendor-stack](https://github.com/JupiterOne/vendor-stack) repository on GitHub is automatically used to enrich the properties of the vendor asset when a new integration i
We should add: "This will not overwrite or replace any custom changes you've made directly to the Vendor entities."

2021-12-15 20:05 UTC, erkangz commented on release-notes/2021-86.md
> +  AWS `Access Bucket and objects not public` aligns with J1 `public: false`
```suggestion
  - AWS `Access Public` aligns with J1 `public: true`
  - AWS `Access Objects can be public` aligns with J1 `public: undefined`
  - AWS `Access Bucket and objects not public` aligns with J1 `public: false`
```

2021-12-15 20:05 UTC, erkangz commented on release-notes/2021-86.md
> +Issues can now discover outside collaborators for CREATED and ASSIGNED relationships.
Can we give an example question/query?

2021-12-15 20:05 UTC, erkangz commented on release-notes/2021-86.md
> +- To import mobile device entities you need to adjust your permissions in your Google Workspace account:
add an empty line after this to be safe

2021-12-15 22:27 UTC, AnneNielsenJ1 commented on release-notes/2021-86.md
> +- Account administrations can now parameterize sensitive values such as secrets for use in J1QL queries and questions without exposing the values.
Users in the Administrator group that have the "All Access" Admin permission. I guess "Organization Admin" would be more accurate than "Account Admin"

2021-12-16 18:43 UTC, erkangz submitted a review, later dismissed

2021-12-16 20:12 UTC, janettelynch approved these changes

2021-12-16 20:12 UTC, merged