Updating Main
JupiterOne/docs pull request #445
Opened 2022-07-13 16:31 UTC by janettelynch

2022-07-13 16:43 UTC, ninetreats requested changes

2022-07-13 16:43 UTC, ninetreats commented on integrations.config.yaml
> +  - projectName: graph-now
@janettelynch did you mean to change this graph-now?  or did I accidentally do it in my pr? The repo name is graph-nowsecure

2022-07-13 16:45 UTC, janettelynch commented on integrations.config.yaml
> +  - projectName: graph-now
No, I don't think I did.

2022-07-14 13:14 UTC, chasen-bettinger approved these changes

2022-07-14 13:17 UTC, merged