Doc 92 - Critical Assets Article
JupiterOne/docs pull request #494
Opened 2022-08-19 16:43 UTC by janettelynch

@a-u-h-g Here is a first draft of an article that groups all the previously disparate info about critical assets. Let me know if there are any errors or other info you would like me to add. Thanks.

2022-08-22 15:27 UTC, a-u-h-g requested changes

2022-08-22 15:27 UTC, a-u-h-g commented on knowledgeBase/asset-management/critical-assets.md
> +![](C:\Users\lynch\OneDrive\Documents\GitHub\docs\knowledgeBase\assets\assets-landing.png)
these image addresses should be pointing to the relative file path in the github repo - currently pointing to your local machine's hard drive

2022-08-22 15:27 UTC, a-u-h-g commented on knowledgeBase/asset-management/critical-assets.md
> +Click ![](C:\Users\lynch\OneDrive\Documents\GitHub\docs\knowledgeBase\assets\icons\gear.png) to edit the critical asset definition default values. You can use classes, properties, and values to defin
these image addresses should be pointing to the relative file path in the github repo - currently pointing to your local machine's hard drive

2022-08-22 15:27 UTC, a-u-h-g commented on knowledgeBase/asset-management/critical-assets.md
> +![](C:\Users\lynch\OneDrive\Documents\GitHub\docs\knowledgeBase\assets\asset-definition.png)
these image addresses should be pointing to the relative file path in the github repo - currently pointing to your local machine's hard drive

2022-08-22 15:27 UTC, a-u-h-g commented on knowledgeBase/asset-management/critical-assets.md
> +![0o](C:\Users\lynch\OneDrive\Documents\GitHub\docs\knowledgeBase\assets\problems-query.png)
this one has a subheading of '0o'? also these image addresses should be pointing to the relative file path in the github repo - currently pointing to your local machine's hard drive

2022-08-22 16:14 UTC, a-u-h-g commented on knowledgeBase/asset-management/critical-assets.md
> +Click ![](C:\Users\lynch\OneDrive\Documents\GitHub\docs\knowledgeBase\assets\icons\gear.png) to edit the critical asset definition default values. You can use classes, properties, and values to defin
this one still needs to be fixed I think

2022-08-22 16:14 UTC, a-u-h-g commented on knowledgeBase/asset-management/critical-assets.md
> +![0o](C:\Users\lynch\OneDrive\Documents\GitHub\docs\knowledgeBase\assets\problems-query.png)
Do we want '0o' as the mouseover text for some reason?

2022-08-24 18:28 UTC, a-u-h-g approved these changes

2022-08-25 17:13 UTC, sarabeth approved these changes

2022-08-25 17:15 UTC, merged