DOC-164
JupiterOne/docs pull request #539
Opened 2022-09-28 18:25 UTC by janettelynch

2022-09-28 18:28 UTC, maya-shankar requested changes

2022-09-28 18:28 UTC, maya-shankar commented on knowledgeBase/APIs/jupiterone-api.md
> +  - `hardDelete` - this flag completely removes all information related to the relationship and is not recoverable.
```suggestion
  - `hardDelete` - this flag completely removes all information related to the entity and is not recoverable.
```

2022-09-28 18:28 UTC, maya-shankar commented on knowledgeBase/APIs/jupiterone-api.md
>  ### Delete Relationship
Everything below would remain the same as it was, but `hardDelete` would be added just it was in the step above. Sorry about the confusion! So it would still be:
```
mutation DeleteRelationship (
  $relationshipId: String!
  $hardDelete: Boolean
) {
  deleteRelationship (
    relationshipId: $relationshipId,
    hardDelete: $hardDelete,
  ) {
    relationship {
      _id
      ...
    }
...
```

2022-10-03 13:36 UTC, janettelynch commented on knowledgeBase/APIs/jupiterone-api.md
>  ### Delete Relationship
@maya-shankar I'm not sure if there is an action for me in your above comment or is everything ready to go?

2022-10-03 14:13 UTC, maya-shankar commented on knowledgeBase/APIs/jupiterone-api.md
>  ### Delete Relationship
Yes, please keep the `mutation DeleteRelationship` section the same as it was, with the only change being the addition of `$hardDelete: Boolean` as shown above in my comment. It looks to me like you've replaced `DeleteRelationship` with `DeleteEntity` on line 847.

2022-10-04 20:15 UTC, maya-shankar commented on knowledgeBase/APIs/jupiterone-api.md
> +  "entityId": "<an entity Id (entity._id)>",
Please update this to `relationshipId`

2022-10-05 12:52 UTC, chasen-bettinger approved these changes

2022-10-05 16:43 UTC, merged