DOC-221 New Rate-Limiting Article.
JupiterOne/docs pull request #652
Opened 2023-01-27 18:57 UTC by janettelynch

2023-01-31 16:48 UTC, plfx submitted a review, later dismissed

2023-02-02 13:40 UTC, benrj requested changes

2023-02-02 13:40 UTC, benrj commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +The default rate of J1QL queries is`120 tokens per 1-minute period`.
```suggestion
The default rate of J1QL queries is`120 tokens per 2-minute period`.
```

2023-02-02 13:40 UTC, benrj commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- JupiterOne declines queries when the rate exceeds 120 tokens per 1-minute period.
```suggestion
- JupiterOne declines queries when the rate exceeds 120 tokens per 2-minute period.
```

2023-02-02 13:40 UTC, benrj commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- **Average rate allowed:** 2 J1QL queries per second.
```suggestion
- **Average rate allowed:** 1 J1QL query per second.
```

2023-02-02 13:40 UTC, benrj commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- **Configurable:** JupiterOne can adjust this rate limit on your behalf. Contact your J1 administrator.
I'm not sure who is best to make a determination on this point, but I think we want to tie increase or removal of this limit to some kind of business value.   E.g. do we automatically approve all requests from enterprise customers to up to the next level (has been our typical first upgrade)?  

Maybe we could implement something like the following:

**Default limit**: 120 tokens / 120 seconds
**No questions asked upgrade for enterprise customers**: 60 tokens / 60 seconds
**Request for approval**: 120 tokens / 60 seconds
**Not public, select customers only**: no rate limit

And then we'd need to determine what that request for approval process looks like.

@a-u-h-g

2023-02-02 16:46 UTC, a-u-h-g reviewed
Some comments

2023-02-02 16:46 UTC, a-u-h-g commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +J1QL queries executed via the [J1 public API](./jupiterone-api.md) are rate-limited separately from [GraphQL API invocations](./rate-limiting.md). Each J1QL query uses one token. All queries executed
```suggestion
J1QL queries executed via the [J1 public API](./jupiterone-api.md) are rate-limited separately from [GraphQL API invocations](./rate-limiting.md). Each J1QL query consumes one request token. All queries executed via the J1 public API count towards the rate limit. This count includes user-initiated application queries (such as search and J1 Insights) and queries via the J1 public API.
```

2023-02-02 16:46 UTC, a-u-h-g commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- **Average rate allowed:** 2 J1QL queries per second.
@benrj is this correct? avg rate allowed is 2 queries / sec?

2023-02-02 16:46 UTC, a-u-h-g commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- **Configurable:** JupiterOne can adjust this rate limit on your behalf. Contact your J1 administrator.
Agreed with the above proposal. How do you think we should change our current public facing info in sales purchase orders if at all? "30 requests/min = default, 60 requests/min = no question upgrade for enterprise"

2023-02-02 16:49 UTC, benrj commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- **Average rate allowed:** 2 J1QL queries per second.
It should be 1 query per second at the default level.

2023-02-02 21:43 UTC, janettelynch commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- **Configurable:** JupiterOne can adjust this rate limit on your behalf. Contact your J1 administrator.
@benrj Can we make it a bit more reader friendly this way:

Default limit: 120 tokens / 120 seconds
Enterprise user upgrade: 60 tokens / 60 seconds
Request for approval: 120 tokens / 60 seconds
Select users: no rate limit


So, I'm replacing lines 9-12 with the above?

2023-02-03 14:02 UTC, benrj commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- **Configurable:** JupiterOne can adjust this rate limit on your behalf. Contact your J1 administrator.
I would suggest replacing just line 12 with:

```
Enterprise customers are eligible for a rate limit increase up to 120 tokens / 60 seconds, subject to usage analysis and approval.  Contact your TSE to request an increase.

All customers should incorporate retry with backoff in response to rate limiting responses from the J1 API.
```

2023-02-06 17:39 UTC, benrj commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- Request for approval: 120 tokens/60 seconds
```suggestion
```
I think this is redundant.

2023-02-06 17:40 UTC, benrj commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- Enterprise user upgrade: 60 tokens/60 seconds
```suggestion
- Enterprise limit (available on request): 60 tokens/60 seconds
```

2023-02-06 17:57 UTC, janettelynch commented on knowledgeBase/APIs/rate-limiting-j1ql.md
> +- Request for approval: 120 tokens/60 seconds
Ok, removing line 9. Thanks!

2023-02-06 23:12 UTC, benrj approved these changes

2023-02-07 18:19 UTC, sarabeth approved these changes

2023-02-08 16:47 UTC, merged