Add FAQ for AWS Throttling
JupiterOne/docs pull request #717
Opened 2023-03-22 20:15 UTC by ndowmon

Added information on how JupiterOne handles rate limiting, and how JupiterOne can further tune the number of requests that we make.

2023-03-22 20:21 UTC, collierkirkland requested changes

2023-03-22 20:21 UTC, collierkirkland commented on knowledgeBase/APIs_and-integrations/cloud-infrastructure/faqs-aws.md
> +AWS APIs do not provide proactive rate limit headers. Instead, the JupiterOne AWS Integration tracks the number of API calls made during each integration execution, and attempts to avoid throttling u
([similar to the AWS implementation for rate limiting](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html)).

2023-03-22 20:21 UTC, collierkirkland commented on knowledgeBase/APIs_and-integrations/cloud-infrastructure/faqs-aws.md
> +If users are still experiencing throttling on their AWS APIs, JupiterOne can further tune the amount of requests per second that the JupiterOne AWS Integration is allowed to make.
Does the user need to reach out to J1 for us to apply further tuning?

2023-03-22 20:22 UTC, ndowmon commented on knowledgeBase/APIs_and-integrations/cloud-infrastructure/faqs-aws.md
> +If users are still experiencing throttling on their AWS APIs, JupiterOne can further tune the amount of requests per second that the JupiterOne AWS Integration is allowed to make.
@collierkirkland yes they do. Any thoughts on what we should say here?

2023-03-22 20:29 UTC, collierkirkland commented on knowledgeBase/APIs_and-integrations/cloud-infrastructure/faqs-aws.md
> +If users are still experiencing throttling on their AWS APIs, JupiterOne can further tune the amount of requests per second that the JupiterOne AWS Integration is allowed to make.
Depending on who the user needs to reach out to, we could provide a link directing them to the proper channel.

Something along the lines of:

"If AWS API throttling continues to impact the JupiterOne AWS integration, contact  [link to proper channel here] for assistance in further tuning the integration to increase the amount of requests per second."

Thoughts?

2023-04-17 19:57 UTC, collierkirkland approved these changes

2023-04-17 21:42 UTC, merged